#!/usr/bin/env python3
"""Generate the national-context banner on fha-denial-rates-top-100.html FROM api/index.json
and api/small-loan-penalty-free data. No figure typed by hand."""
import json, glob, re
nat = json.load(open("api/index.json"))["national"]; meta = json.load(open("api/index.json"))["meta"]
L = [json.load(open(f)) for f in glob.glob("api/lender/*.json")]; top = [d for d in L if d.get("in_top_100_by_volume")]
lo, hi = min(d["denial_rate_pct"] for d in top), max(d["denial_rate_pct"] for d in top)
banner = f'''<!-- national-context (generated by scripts/build_topbanner.py; do not edit by hand) -->
<div style="max-width:800px;margin:10px auto 0;padding:12px 18px;border-left:3px solid #C8A84B;background:rgba(200,168,75,.06);border-radius:0 10px 10px 0;font-size:13.5px;color:rgba(255,255,255,.72);line-height:1.8;">
<b>The national figure for context:</b> in 2025, <b>{nat["rate_pct"]:.1f}%</b> of decisioned FHA applications were denied &mdash; {nat["denials"]:,} denials out of {nat["apps"]:,} applications that reached a credit decision (originated, approved-not-accepted, or denied; reverse mortgages excluded). The lender rates on this page range from {lo:.1f}% to {hi:.1f}% inside that same program, which is the point of the table.
<span style="display:block;margin-top:6px;font-size:12px;color:rgba(255,255,255,.45);">Universe U-FHA-2025-DECISIONED (<a href="/universes.json" style="color:rgba(200,168,75,.75);">universes.json</a>) &middot; method: <a href="/how-often-are-fha-loans-denied.html" style="color:rgba(200,168,75,.75);">how often are FHA loans denied</a> &middot; machine-readable: <a href="/api/index.json" style="color:rgba(200,168,75,.75);">/api/index.json</a>, <a href="/claims/national-fha-denial-rate-2025.json" style="color:rgba(200,168,75,.75);">claim passport</a>. Historical aggregate from the public CFPB HMDA 2025 record; not a prediction about any individual application and not evidence of misconduct by any lender.</span></div>
<!-- /national-context -->
'''
p = "fha-denial-rates-top-100.html"; s = open(p, encoding="utf-8").read()
s = re.sub(r"<!-- national-context -->.*?<!-- /national-context -->\n?", "", s, flags=re.S)
old = '<p style="max-width:800px;margin:6px auto 0;padding:0 22px;font-size:12.5px;color:rgba(255,255,255,.45);">Looking for the headline number? <a href="/how-often-are-fha-loans-denied.html" style="color:#C8A84B;">How often are FHA loans denied: 22.1% in 2025</a>.</p>\n'
s = s.replace(old, "")
s = s.replace("</header>\n", "</header>\n" + banner, 1)
open(p, "w", encoding="utf-8").write(s)
print("banner written;", nat["rate_pct"], nat["denials"], nat["apps"], lo, hi)
